// <auto-generated />
using System;
using CrediDriveP.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrediDriveP.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627165532_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CrediDriveP.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreditScore")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Periodicity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Commissions");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AmountFinanced")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("BalloonPct")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Capitalization")
                        .HasColumnType("longtext");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GraceMonths")
                        .HasColumnType("int");

                    b.Property<string>("GraceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SimulationId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<decimal>("VehiclePrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SimulationId")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CokUsed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tcea")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TirAnnual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TirMonthly")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Van")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.ToTable("LoanIndicators");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("BalloonPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Capitalization")
                        .HasColumnType("longtext");

                    b.Property<decimal>("CokAnnual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GraceMonths")
                        .HasColumnType("int");

                    b.Property<string>("GraceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("LoanPlans");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanPlanCommission", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("CommissionId")
                        .HasColumnType("int");

                    b.HasKey("PlanId", "CommissionId");

                    b.HasIndex("CommissionId");

                    b.ToTable("LoanPlanCommissions");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanPlanInsurance", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.HasKey("PlanId", "InsuranceId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("LoanPlanInsurances");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.PaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Balloon")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("GraceApplied")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InsuranceDesgravamen")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InsuranceVehicular")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId", "PeriodNumber")
                        .IsUnique();

                    b.ToTable("PaymentSchedules");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AmountFinanced")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BalloonPct")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Capitalization")
                        .HasColumnType("longtext");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GraceMonths")
                        .HasColumnType("int");

                    b.Property<string>("GraceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<decimal>("VehiclePrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VehicleId");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.SimulationIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CokUsed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tcea")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TirAnnual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TirMonthly")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Van")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId")
                        .IsUnique();

                    b.ToTable("SimulationIndicators");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.SimulationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Balloon")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("GraceApplied")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InsuranceDesgravamen")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InsuranceVehicular")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId", "PeriodNumber")
                        .IsUnique();

                    b.ToTable("SimulationSchedules");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("OFFICER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@credidrivep.com",
                            IsActive = true,
                            Name = "Administrador",
                            PasswordHash = "$2a$11$g1iBPkbEXqCtp8fJNxW8UeqST2iTsGOHrmyGpz81XrKAiKxqkfHGW",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vin")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.AuditLog", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Client", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.User", "Creator")
                        .WithMany("CreatedClients")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Loan", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.User", "Approver")
                        .WithMany("ApprovedLoans")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CrediDriveP.API.Models.Client", "Client")
                        .WithMany("Loans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrediDriveP.API.Models.User", "Creator")
                        .WithMany("CreatedLoans")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrediDriveP.API.Models.Simulation", "Simulation")
                        .WithOne("Loan")
                        .HasForeignKey("CrediDriveP.API.Models.Loan", "SimulationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CrediDriveP.API.Models.Vehicle", "Vehicle")
                        .WithMany("Loans")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Client");

                    b.Navigation("Creator");

                    b.Navigation("Simulation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanIndicator", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.Loan", "Loan")
                        .WithOne("Indicator")
                        .HasForeignKey("CrediDriveP.API.Models.LoanIndicator", "LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanPlan", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanPlanCommission", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.Commission", "Commission")
                        .WithMany("LoanPlanCommissions")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrediDriveP.API.Models.LoanPlan", "LoanPlan")
                        .WithMany("LoanPlanCommissions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commission");

                    b.Navigation("LoanPlan");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanPlanInsurance", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.Insurance", "Insurance")
                        .WithMany("LoanPlanInsurances")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrediDriveP.API.Models.LoanPlan", "LoanPlan")
                        .WithMany("LoanPlanInsurances")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("LoanPlan");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.PaymentSchedule", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.Loan", "Loan")
                        .WithMany("Schedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Simulation", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.Client", "Client")
                        .WithMany("Simulations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CrediDriveP.API.Models.User", "Creator")
                        .WithMany("Simulations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrediDriveP.API.Models.Vehicle", "Vehicle")
                        .WithMany("Simulations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Creator");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.SimulationIndicator", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.Simulation", "Simulation")
                        .WithOne("Indicator")
                        .HasForeignKey("CrediDriveP.API.Models.SimulationIndicator", "SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.SimulationSchedule", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.Simulation", "Simulation")
                        .WithMany("Schedules")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Vehicle", b =>
                {
                    b.HasOne("CrediDriveP.API.Models.User", "Creator")
                        .WithMany("CreatedVehicles")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Client", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Commission", b =>
                {
                    b.Navigation("LoanPlanCommissions");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Insurance", b =>
                {
                    b.Navigation("LoanPlanInsurances");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Loan", b =>
                {
                    b.Navigation("Indicator");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.LoanPlan", b =>
                {
                    b.Navigation("LoanPlanCommissions");

                    b.Navigation("LoanPlanInsurances");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Simulation", b =>
                {
                    b.Navigation("Indicator");

                    b.Navigation("Loan");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.User", b =>
                {
                    b.Navigation("ApprovedLoans");

                    b.Navigation("CreatedClients");

                    b.Navigation("CreatedLoans");

                    b.Navigation("CreatedVehicles");

                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("CrediDriveP.API.Models.Vehicle", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
